### PR TITLE
Rename SimpleAverage in decider.py 

### PR DESCRIPTION
**Pull request by chenyugoal**
## What is the issue?
Rename SimpleAverage in decider.py to SimpleArgmaxAverage and propagate changes #115 
The issue was put up by @levinwil 

## What changes?
I've done the search and replaced all 'SimpleAverage' with 'SimpleArgmaxAverage'. 
There are two types: 
- One is 'from deciders import SimpleAverage', 
- the other is 'from proglearn import SimpleAverage'. I replaced them all.

### CODE REVIEW

**Comment by jdey4** [comment]
@chenyugoal please solve the merge conflicts.

**Comment by chenyugoal** [comment]
Finally, it passed the Travis CI build! 
So the problem might be:
I was doing 'Pull' from my repo, rather than from neurodata's repo. Therefore, it caused no changes to the file. And I could not get the correct version, thus failing the Travis again and again.

**Review by sampan501 — APPROVED** [review]

**Comment by hhelm10** [comment]
@levinwil @jovo can i suggest a(nother) change to ArgmaxSimpleAverage..?

**Comment by levinwil** [comment]
Sure!

**Pull request merged**
