### PR TITLE
Unittest for l2f

### PR DESCRIPTION
**Pull request by latasianguy**
Issue #100 , Sprint 0.

Add unit tests for LifelongClassificationForest class.
Implemented methods to check the default initialization attributes and input validation for initialization.

### CODE REVIEW

**Comment by latasianguy** [comment]
@jdey4  new branch, didn't work

**Comment by jdey4** [comment]
Could you do the unit_test locally on your laptop? I think, there is an indentation problem in line 96 of forest.py. Could you fix that?

**Comment by latasianguy** [comment]
It's weird because my commits have not edited forest.py, could it be a result of another PR?

**Comment by latasianguy** [comment]
image
Local test results.

**Comment by jdey4** [comment]
Maybe your unittests are accessing forest.py that no one else's PR did. There is a bug in forest.py. If you fix the indentation, it can be done in a single PR.

**Comment by latasianguy** [comment]
@jdey4 finally passed, had to rename some things and fixed the indentation in forests.py

**Review by jdey4 — APPROVED** [review]

**Pull request merged**
