### PR TITLE
Predict to decide rename

### PR DESCRIPTION
**Pull request by levinwil**
Closing Issue #145

### CODE REVIEW

**Comment by hhelm10** [comment]
@jovo "decide", like "vote", has categorical connotations and doesn't seem to generalize well to non-classiifcation tasks. do you agree/disagree?

moreover, if we eventually want to greater-ML community to contribute to this repo, why deviate from sklearn?

**Comment by levinwil** [comment]
@hhelm10 I am fine with using 'predict' and 'predict_proba', but I would like our convention to be consistent across transformers, voters, and deciders. Currently, in transformer, we have a function called 'transform'; in voters, it is called 'vote'. I was changing deciders to be consistent with the other two. But I am fine going in the other direction as well. Whatever is best.

**Comment by hhelm10** [comment]
yea i see the value in the consistency -- i think in the cases of the transformer / voter the functionality is (relatively) novel / not an emphasis in sklearn and so we have some degree of freedom in naming.

i think the universality of 'predict' in decider-like things removes that degree of freedom for deciders.

**Comment by levinwil** [comment]
One could easily argue that voters should be an sklearn function. It takes in data that happens to be preprocessed through a transformation (as is most data) and it outputs some expected value. That's literally every supervised algorithm ever. Perhaps transform is slightly novel, in the sense that it doesn't obviously fit into an sklearn API as far as I am aware. But, again, I don't care if we go with transform/vote/decide or predict/predict/predict. I just care about consistency. This seems like a very small and unimportant point, and there's already a bunch of docs and experiments and tests written assuming the transform/vote/decide API, so I was just going with the path of least change.

**Comment by hhelm10** [comment]
i think the voters for the problems we currently support can fit in the sklearn framework but i doubt that will hold true for long?

you're right, not a big deal. i'd advocate for 'predict' if the paths are of equal resistance, but if 'decide' is easier then im ok with 'decide'

**Pull request closed without merging**
