### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by ykobaya9**
@levinwil This is the staging branch for the tutorial notebook. Thank you!

### CODE REVIEW

**Comment by levinwil** [comment]
@ykobaya9 you should be creating a branch called "staging" on the neurodata repo, not your own repo. You should be merging into "neurodata:staging" not "ykobaya9:staging"

The neurodata:staging branch current does not exist. Could you please create that branch and then create a PR to merge into it?

**Comment by ykobaya9** [comment]
I see, I'm sorry but I'm not sure how to create a branch in the main repository. Do I clone the original repository and create a branch there?

**Comment by levinwil** [comment]
Yah. I'll actually go ahead and make the branch, so I'm the owner of it. I'll link the branch URL here afterwards :)

**Comment by levinwil** [comment]
@ykobaya9 Here is the new staging branch: https://github.com/neurodata/progressive-learning/tree/staging. Could you please:
1. Make a new PR to the staging branch, following the PR instructions in the contribution guidelines in the docs folder
2. Close this PR, with a comment saying that you made a new PR and link that PR with #<PR number>
3. Close your previous PR, with a comment saying that you made a new PR and link that PR with #<PR number>

**Comment by ykobaya9** [comment]
New PR #259

**Pull request closed without merging**
