### PR TITLE
Tutorial Notebook for label_shuffle

### LINKED ISSUE #75: Reproduce label_shuffle experiment
https://github.com/neurodata/progressive-learning/issues/41

### PR DESCRIPTION
**Pull request by ykobaya9**
This is my second version for the tutorial Jupyter notebook for label_shuffle, which is my sprint 0 issue. closes #75 @jdey4

### CODE REVIEW

**Comment by levinwil** [comment]
@ykobaya9  This is great so far! One modification: we are trying to make sure there are no pickle files saved for tutorials. If possible, could you please modify your tutorial such that the results are saved directly to an array (as opposed to using pickle to save results and then loading them again with unpickle)

**Comment by ykobaya9** [comment]
Thank you for the feedback! I made the changes as requested.

**Comment by levinwil** [comment]
Great! @ykobaya9 this is super small, but could you please get rid of the ‘unpickle’ function definition?

**Comment by levinwil** [comment]
Oh I should've mentioned this before: instead of doing plt.savefig, could you please do plt.show? We don't want users to have files from the tutorials saved outside of the notebooks.

**Comment by levinwil** [comment]
And (I hope this is the last change) the y-axis of the final figure should be "Backwards Transfer Efficiency", not "Transfer Efficiency"

**Comment by ykobaya9** [comment]
I changed the label but didn't regenerate the plot, since I have to rerun the model. Should I have reran the model to regenerate the plot?

**Comment by levinwil** [comment]
@latasianguy Yes please. That would be ideal. Sorry for the inconvenience. I will also back up and say that I think, although this is a step in the right direction, this isn't a 'tutorial' per se. A tutorial should walk a user through the tutorial, on a nearly line-by-line basis (either through text cells or in-line comments in the code) as to what is going on. So you should know what every line of code is doing, including function calls, import statements, and variable assignments. Everything in the tutorial should NEED to be there. As a minor example, the following line declares several colors, assuming several algorithms will be plotted: 'clr = ["#00008B", "#e41a1c", "#a65628", "#377eb8", "#4daf4a", "#984ea3", "#ff7f00", "#CCCC00"]'. But only 2 algorithms are used (L2F and L2N), meaning there are unnecessary colors defined. As another example, there are a bunch of unnecessary imports. 

I would look at this as a way for a new user to just open this repo and look at this tutorial as a "I have no idea what this is. Please hold my hand and walk me through everything in detail so I have an idea of what is going on, how to use it, and the results for when I use it on this label_shuffle experiment." 

Does that make sense?

It's a lot of work. And this is for sure a step in the right direction, if we use the label_shuffle file in the experiments folder as a reference point. But it really should be more detailed and simplified, which will likely take a while - that is why this is a Sprint 1 Issue.

**Comment by ykobaya9** [comment]
Hi @levinwil, I made an update to the tutorial notebook. I removed as much of the redundant or unnecessary code as possible, and added more comments.

**Comment by levinwil** [comment]
@ykobaya9 you should install as described in the README, certainly NOT using sys or pointing to a path on your local computer. After that, use the proglearn package with ‘from proglearn import {forest, network}’

Do you think you understand every line of code in this tutorial and think it is as slim, minimal, and clean as it can be? Please remember everything I commented above. I think this is a step in the right direction, but it’s far from a proper tutorial that mimics the tutorials I linked in the slack here: https://graspy.neurodata.io/tutorial.html

**Review by levinwil — COMMENTED** [review]
1. Should install package as described in README and import as appropriate 
2. Should mimic tutorials here: https://graspy.neurodata.io/tutorial.html

**Comment by ykobaya9** [comment]
Thank you for the feedback, I forgot to remove the sys stuff since I was using it to run locally. Should I perhaps move the functions to a separate file? I'm not sure whether its possible to simplify to the level of some of the simulations in the graspologic tutorials.

**Comment by levinwil** [comment]
I was thinking it would be best to move some functions to another file, if they aren’t already in the label shuffle file in the experiments folder. Keep in mind those exist so I’d try to call those if possible, since they’re the same code - just make sure to explain all hyper parameters, especially hyper parameters to functions you’re calling from another file

**Comment by ykobaya9** [comment]
Hi @levinwil , I moved the functions to a new file to significantly simplify the notebook itself. I think the reason why I didn't call the functions in the experiment folder is that when I import the file, it runs the code that is not part of the function, so it runs the entire experiment.

**Review by levinwil — CHANGES_REQUESTED** [review]
This is great so far!

1. Let's simplify it greatly and just assume you always use UF. So we shouldn't need to ever check if we're using UF or DNN. 
2. For the functions that you do put in other files, can we put those files in a folder within tutorials and call it "functions" 
3. For the functions that you do put in other files, please simplify them as much as possible. For example, plot_bte does not need the alg_name or alg_no. It will always be alg_name = "UF" and alg_no = 0. This does NOT mean to set a default alg_name = "UF", alg_no = 0. This means to go into the code that you are taking out of this notebook and simplify it. These functions were made to account for multiple outside algorithms, as well as UF and DNN. We now only need one algorithm, so we don't need any of that extra stuff. Does that make sense?

**Comment by levinwil** [comment]
@ykobaya9 This is super close to what I would consider ideal! Great work!

Can you make a branch called "staging" and PR into that, then I'll go in and manually change small things that are just me being picky? After that, you can PR into that branch main, and then the tutorial will be complete and on main :)

**Comment by ykobaya9** [comment]
new PR #259

**Pull request closed without merging**
