### PR TITLE
Reproduce rotation_cifar experiment with Jupyter Notebook tutorial

### PR DESCRIPTION
**Pull request by srahul1222**
Writing a tutorial for rotation_cifar (Issue #151 ) 

Sprint 0

### CODE REVIEW

**Comment by jdey4** [comment]
@srahul1222 could you run it on 10 reps and commit the notebook with plots within one notebook. Please see: https://github.com/neurodata/progressive-learning/blob/master/experiments/parity_experiment/experiment.ipynb

**Comment by levinwil** [comment]
@jdey4 If he runs it for fewer trials, it will be extremely noisy. We could theoretically do very few angles (maybe just 0, 45, 90, and 180) and do 1000 reps or so. Thoughts?

@srahul1222 Ideally, as Jayanta said, you would run the experiment and plot within the same notebook. I have one additional request and that is to please use forest.py and network.py for L2F and L2N, respectively, instead of the base progressive learner class. That request is a strong one, as people from Microsoft requested that the tutorials and documentation focus on the use of LifelongClassification{Forest, Network}

**Comment by jdey4** [comment]
@levinwil we have to run it again later. It will be difficult for @srahul1222 to run using many reps.

**Comment by levinwil** [comment]
@jdey4 That is fine with me if you and I run it later. If you want to accept Rahul's tutorial notebook with a reduced number of reps, please be aware that, it will certainly be extremely noisy and difficult to see a pattern of decreasing BTE as angle increases from 0 to 180, especially if we use granularity = 1. And that pattern is the whole point of the tutorial. Hence, my recommendation of reducing the granularity and just performing the experiment on {0, 45, 90, 180} degrees - the patterns will (hopefully) be more easy to see. And, if we do so, he will only have 4 angles to run the experiment on, so he can do more reps. Maybe 1000 might be a bit much, but I just want to make sure that - in our own tutorials especially - when we claim something like positive BTE but decreasing as the angle goes from 0 to 180, we can actually show that pattern. It's therefore important to make sure those the BTE's computed at those 4 angles show a decreasing pattern. One way to do so is to have a high number of reps for each angle. 

How about we do something in the middle: perform the experiment on {0, 45, 90, 180} degrees with 100 reps, see if it looks smooth. If not, increase the reps. Repeat until it looks pretty smoothly decreasing. How does that sound @srahul1222 @jdey4?

**Comment by srahul1222** [comment]
@levinwil @jdey4 Yea, that sounds good. I'll combine the experiment and plot into one notebook and re-run it with 100 reps. For the angles, you mentioned 0, 45, 90, and 180 degrees only -- is there any reason why I shouldn't also try on 135 degrees (granularity = 45)?

**Comment by levinwil** [comment]
@srahul1222 135 degree should be included as well. I just forgot it haha. Also, please use LifelongClassification{Network, Forest} in the new Pull Request if possible, as opposed to the base progressive learner. You can find those classes in network.py and forest.py, respectively. They follow a really similar interface to the progressive learner, so it should be a very easy change that also gets rid of a significant amount of code in your notebook.

**Comment by srahul1222** [comment]
@levinwil Ok cool I'll do that. Should I still keep the results folder with all the pickle files now that both the experiment and plot are in the same notebook? Or is there a way to directly take the output of the experiment and plot it?

**Comment by levinwil** [comment]
@sampan501 there should be no results folder, and no pickle files. You should just save all of the results directly to an array. This is as opposed to writing all results to pickle files, then loading those pickle files into an array. This way, we go directly to the array the pickle files would've given us, without needing to save any pickle files. 

In that vein, could you please get rid of all pickle files and the results folder before making the new PR :)

**Comment by jdey4** [comment]
Due to change in the name from 'master' to 'main', this PR was somehow closed. Could you make the PR again @srahul1222 ?

**Pull request closed without merging**
