### PR TITLE
Added docstrings for the uncertainty forest class in forest.py

### PR DESCRIPTION
**Pull request by bstraus1**

### CODE REVIEW

**Review by jdey4 — COMMENTED** [review]
@bstraus1 see here how they describe the X and Y parameter: https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_blobs.html.

**Comment by bstraus1** [comment]
FYI this issue is a subcomponent of issue #73

**Comment by bstraus1** [comment]
May I be assigned to this issue and removed from #4, #73, and #74 because I will only be completing parts  of those issues.

**Comment by bstraus1** [comment]
1. Can I be assigned to this issue? 
2. This issue should be closed since it has been merged.

**Pull request merged**
