### PR TITLE
Reproduce xor_nxor_exp in Jupyter notebook

### PR DESCRIPTION
**Pull request by emilyachang**
PR for Jupyter notebook tutorial of xor_nxor_exp 
Re: issue #98

### CODE REVIEW

**Comment by levinwil** [comment]
@emilyachang This looks great! Thank you for writing out the math and everything!

If possible, could you please replace your UF instance with an instance of official UncertaintyForest class in forest.py and your progressive learner instance (which is a LifelongClassificationForest) with an instance of the official LifelongClassificationForest implementation in forest.py?

MSR people said to focus docs and tutorials on forest.py (and network.py, but that's outside of the scope of this tutorial). So it would be much appreciated if you could convert to use the classes in forest.py :)

**Comment by levinwil** [comment]
@jdey4 Do you think that this tutorial should be saving/loading pickle files, or to alleviate any pickle files as with the other tutorials? I personally think we should avoid saving any pickle files. That should be a super easy fix for this tutorial, since it already has everything saved to an array with the same name and data as those that are being loaded from pickle files - but I wanted to confirm with you.

**Comment by jdey4** [comment]
@levinwil yeah I agree with you. We do not need the pickle files for the tutorials. I personally save them as I do not want to run them again when I have to make slides or figures for jovo.

**Comment by levinwil** [comment]
@emilyachang Just as a quick summary: 

1. Please replace your UF instance with an instance of official UncertaintyForest class in forest.py and your progressive learner instance (which is a LifelongClassificationForest) with an instance of the official LifelongClassificationForest implementation in forest.py

2. Please get rid of the cells that save and load your results in pickle files. There is no need and it just clutters the notebook/repo. To be more pointed, I am referring to the cells that starts with 'with open('./result/mean_xor_nxor.pickle','wb') as f:' and 'def unpickle(file):'. You will also need to get rid of the lines that call the 'unpick' function, which shouldn't be a problem since you already have the 'mean_error' and 'std_error' arrays saved and to variables and they correspond to the same values you would've gotten from the unpick function.

**Comment by jdey4** [comment]
Due to change in the name from 'master' to 'main', this PR was somehow closed. Could you make the PR again @emilyachang ?

**Pull request closed without merging**
